language: java
jdk: oraclejdk8
script: gradle build
cache:
  directories:
    - .gradle
    - gradle
    - $HOME/.gradle
notifications: # always / change / never
  on_failure: always
  on_success: never
